Assesing that the model is still qorking fine or theres a model drift/population drift
- Assess population density - population of new applicants vs population of training data
- Model maintainance - assess model in light of new data (scheduled) or number of applicants as benchmark
- Population acceptability index (PSI) - compare populations (new data vs original data) - shows two populations differ with respect to a feature using discrete categories of the feature

PSI measures distribution change

 - < 0.10 Little to no change Safe

- 0.10 – 0.25 Moderate change Investigate

- more than 0.25 Major shift Rebuild model

- 1 absolute difference

### Import libraries

In [1]:
import numpy as np
import pandas as pd

### Loading data

#### Import data

In [2]:
#preserve indexes for correct matching
loan_data_inputs_train = pd.read_csv('loan_data_inputs_train.csv', index_col = 0) #use content of the first column as indexes
# loan_data_target_train = pd.read_csv('loan_data_targets_train.csv', index_col = 0, header = None) #don't import header for the df with targets
loan_data_target_train = pd.read_csv('loan_data_targets_train.csv', index_col = 0)
loan_data_inputs_test = pd.read_csv('loan_data_inputs_test.csv', index_col = 0)
loan_data_target_test = pd.read_csv('loan_data_targets_test.csv', index_col = 0)

In [3]:
# Here we import the new data.
loan_data_backup = pd.read_csv('loan_data_2015.csv')

C:\Users\lkima\AppData\Local\Temp\ipykernel_25768\3437895857.py:2: DtypeWarning: Columns (19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  loan_data_backup = pd.read_csv('loan_data_2015.csv')

#### Explore data

In [4]:
loan_data = loan_data_backup.copy()

In [5]:
pd.options.display.max_columns = None
#pd.options.display.max_rows = None
# Sets the pandas dataframe options to display all columns/ rows.

In [6]:
loan_data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,68444620,73334399,35000,35000,35000.0,60 months,11.99,778.38,C,C1,Foreign Service Officer,10+ years,MORTGAGE,128000.0,Source Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,Home improvement,200xx,DC,6.46,0.0,Feb-90,0.0,46.0,NaN,17.0,0.0,14277,27.4,46.0,w,35000.0,35000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,56.0,1,INDIVIDUAL,NaN,NaN,NaN,0.0,321.0,146867.0,1.0,11.0,0.0,0.0,28.0,35367.0,49.3,0.0,1.0,5020.0,40.1,52200.0,1.0,4.0,0.0
1,68547583,73437441,8650,8650,8650.0,36 months,5.32,260.50,A,A1,Associate Consultant,< 1 year,MORTGAGE,100000.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,462xx,IN,7.28,0.0,Jul-01,0.0,NaN,NaN,15.0,0.0,7158,26.7,24.0,w,8650.0,8650.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,165450.0,0.0,1.0,1.0,1.0,11.0,24041.0,88.8,0.0,3.0,3081.0,57.9,26800.0,1.0,0.0,5.0
2,67849662,72708407,4225,4225,4225.0,36 months,14.85,146.16,C,C5,mechanic,5 years,RENT,35000.0,Source Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,672xx,KS,15.22,2.0,Jul-11,0.0,18.0,NaN,6.0,0.0,1058,24.6,6.0,w,4225.0,4225.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,4888.0,0.0,1.0,0.0,0.0,47.0,3830.0,21.9,0.0,0.0,367.0,22.4,4300.0,0.0,0.0,0.0
3,68506885,73396712,10000,10000,10000.0,60 months,11.99,222.40,C,C1,CARDIOVASCULAR TECH,10+ years,RENT,42500.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,460xx,IN,31.04,0.0,Dec-98,1.0,NaN,NaN,10.0,0.0,5812,40.9,23.0,w,10000.0,10000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,41166.0,1.0,3.0,0.0,2.0,13.0,35354.0,75.5,1.0,1.0,3118.0,67.4,14200.0,1.0,1.0,1.0
4,68341763,72928789,20000,20000,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-00,0.0,NaN,NaN,6.0,0.0,7869,56.2,18.0,w,20000.0,20000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Dec-15,0.0,NaN,1,JOINT,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,72.8,0.0,2.0,2081.0,64.7,14000.0,2.0,5.0,1.0

In [7]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421094 entries, 0 to 421093
Data columns (total 74 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           421094 non-null  int64
 1   member_id                    421094 non-null  int64
 2   loan_amnt                    421094 non-null  int64
 3   funded_amnt                  421094 non-null  int64
 4   funded_amnt_inv              421094 non-null  float64
 5   term                         421094 non-null  object
 6   int_rate                     421094 non-null  float64
 7   installment                  421094 non-null  float64
 8   grade                        421094 non-null  object
 9   sub_grade                    421094 non-null  object
 10  emp_title                    397220 non-null  object
 11  emp_length                   397277 non-null  object
 12  home_ownership               421094 non-null  object
 13  annual_inc                   421094 non-null  float64
 14  verification_status          421094 non-null  object
 15  issue_d                      421094 non-null  object
 16  loan_status                  421094 non-null  object
 17  pymnt_plan                   421094 non-null  object
 18  url                          421094 non-null  object
 19  desc                         45 non-null      object
 20  purpose                      421094 non-null  object
 21  title                        420962 non-null  object
 22  zip_code                     421094 non-null  object
 23  addr_state                   421094 non-null  object
 24  dti                          421094 non-null  float64
 25  delinq_2yrs                  421094 non-null  float64
 26  earliest_cr_line             421094 non-null  object
 27  inq_last_6mths               421094 non-null  float64
 28  mths_since_last_delinq       217133 non-null  float64
 29  mths_since_last_record       74415 non-null   float64
 30  open_acc                     421094 non-null  float64
 31  pub_rec                      421094 non-null  float64
 32  revol_bal                    421094 non-null  int64
 33  revol_util                   420932 non-null  float64
 34  total_acc                    421094 non-null  float64
 35  initial_list_status          421094 non-null  object
 36  out_prncp                    421094 non-null  float64
 37  out_prncp_inv                421094 non-null  float64
 38  total_pymnt                  421094 non-null  float64
 39  total_pymnt_inv              421094 non-null  float64
 40  total_rec_prncp              421094 non-null  float64
 41  total_rec_int                421094 non-null  float64
 42  total_rec_late_fee           421094 non-null  float64
 43  recoveries                   421094 non-null  float64
 44  collection_recovery_fee      421094 non-null  float64
 45  last_pymnt_d                 403811 non-null  object
 46  last_pymnt_amnt              421094 non-null  float64
 47  next_pymnt_d                 395337 non-null  object
 48  last_credit_pull_d           421083 non-null  object
 49  collections_12_mths_ex_med   421094 non-null  float64
 50  mths_since_last_major_derog  122729 non-null  float64
 51  policy_code                  421094 non-null  int64
 52  application_type             421094 non-null  object
 53  annual_inc_joint             511 non-null     float64
 54  dti_joint                    509 non-null     float64
 55  verification_status_joint    511 non-null     object
 56  acc_now_delinq               421094 non-null  float64
 57  tot_coll_amt                 421094 non-null  float64
 58  tot_cur_bal                  421094 non-null  float64
 59  open_acc_6m                  21372 non-null   float64
 60  open_il_6m                   21372 non-null   float64
 61  open_il_12m                  21372 non-null   float64
 62  open_il_24m                  21372 non-null   float64
 63  mths_since_rcnt_il           20810 non-null   float64
 64  total_bal_il                 21372 non-null   float64
 65  il_util                      18617 non-null   float64
 66  open_rv_12m                  21372 non-null   float64
 67  open_rv_24m                  21372 non-null   float64
 68  max_bal_bc                   21372 non-null   float64
 69  all_util                     21372 non-null   float64
 70  total_rev_hi_lim             421094 non-null  float64
 71  inq_fi                       21372 non-null   float64
 72  total_cu_tl                  21372 non-null   float64
 73  inq_last_12m                 21372 non-null   float64
dtypes: float64(45), int64(6), object(23)
memory usage: 237.7+ MB

## Population Stability Index

####  Preprocessing

We have to perform the exact same data preprocessing, fine-classing, and coarse classing on the new data, in order to be able to calculate statistics for the exact same variables to the ones we used for training and testing the PD model.

Employment length

In [8]:
loan_data['emp_length'].unique()

array(['10+ years', '< 1 year', '5 years', '3 years', '4 years', nan,
       '2 years', '8 years', '9 years', '1 year', '6 years', '7 years'],
      dtype=object)

In [9]:
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace(r'\+', ' ', regex=True)
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('n/a',  str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '')

In [10]:
type(loan_data['emp_length_int'][0])

str

In [11]:
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'])

In [12]:
type(loan_data['emp_length_int'][0])

numpy.float64

Earliest credit line

In [13]:
loan_data['earliest_cr_line']

0         Feb-90
1         Jul-01
2         Jul-11
3         Dec-98
4         Aug-00
           ...
421089    Sep-04
421090    Mar-74
421091    Sep-03
421092    Oct-03
421093    Dec-01
Name: earliest_cr_line, Length: 421094, dtype: object

In [14]:
loan_data['earliest_cr_line_date'] = pd.to_datetime(
    loan_data['earliest_cr_line'],
    format='%b-%y'
)

loan_data['earliest_cr_line_date'] = loan_data['earliest_cr_line_date'].apply(
    lambda x: x if x.year <= 2017 else x.replace(year=x.year - 100)
)

In [15]:
type(loan_data['earliest_cr_line_date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [19]:
#check how many months/days past referencing a specific start date
# 1. Create the reference date object
ref_date = pd.to_datetime('2018-12-01')

In [20]:
# 2. Subtract the column from the reference date
loan_data['days_since_earliest_cr_line'] = ref_date - loan_data['earliest_cr_line_date']

In [21]:
# 2. Extract the number of days (.dt.days)
# 3. Divide by 30.44 and round to convert to months
loan_data['mths_since_earliest_cr_line'] = np.round(loan_data['days_since_earliest_cr_line'].dt.days / 30.44).astype('Int64')

In [22]:
# There are 2303 such values.
loan_data.loc[: , ['earliest_cr_line', 'earliest_cr_line_date', 'mths_since_earliest_cr_line']][loan_data['mths_since_earliest_cr_line'] < 0]

Empty DataFrame
Columns: [earliest_cr_line, earliest_cr_line_date, mths_since_earliest_cr_line]
Index: []

Term

In [23]:
loan_data['term']

0          60 months
1          36 months
2          36 months
3          60 months
4          60 months
             ...
421089     36 months
421090     36 months
421091     60 months
421092     60 months
421093     36 months
Name: term, Length: 421094, dtype: object

In [24]:
loan_data['term'].describe()

count         421094
unique             2
top        36 months
freq          283172
Name: term, dtype: object

In [25]:
loan_data['term_int'] = loan_data['term'].str.replace(' months', '')

In [26]:
loan_data['term_int']

0          60
1          36
2          36
3          60
4          60
         ...
421089     36
421090     36
421091     60
421092     60
421093     36
Name: term_int, Length: 421094, dtype: object

In [27]:
type(loan_data['term_int'])
type(loan_data['term_int'][25])

str

In [28]:
loan_data['term_int'] = pd.to_numeric(loan_data['term'].str.replace(' months', ''))
loan_data['term_int']

0         60
1         36
2         36
3         60
4         60
          ..
421089    36
421090    36
421091    60
421092    60
421093    36
Name: term_int, Length: 421094, dtype: int64

In [29]:
type(loan_data['term_int'][0])

numpy.int64

Time since loan was funded

In [31]:
loan_data['issue_d_date'] = pd.to_datetime(loan_data['issue_d'], format = '%b-%y')

In [32]:
issue_d_ref_date = '2018-12-01'
loan_data['days_since_issue_d'] = ref_date - loan_data['issue_d_date']

In [33]:
loan_data['mths_since_issue_d'] = np.round(loan_data['days_since_issue_d'].dt.days / 30.44).astype('Int64')

### Data preparation: preprocessing discrete variables